apiVersion: apps/v1
kind: Deployment
metadata:
  name: udegram
  labels:
    app: udegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udegram
  template:
    metadata:
      labels:
        app: udegram
    spec:
      containers:
      - name: hello
        image: adrianbadarau/udegram-api
        ports:
        - containerPort: 8080
      - name: hello
        image: adrianbadarau/udegram-api
        ports:
        - containerPort: 8080
